CREATE TABLE `weddingbudget`.`itemviews` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `views` VARCHAR(45) NULL,
  `date` VARCHAR(45) NULL,
  `timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`));


ALTER TABLE `weddingbudget`.`itemviews` 
ADD COLUMN `itemid` VARCHAR(255) NULL AFTER `id`;

